server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: "info"

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log
    pipeline_stages:
    - json:
        expressions:
            timestamp: timestamp
            message: message
            thread_name: thread_name
            level: level
            trace_id: traceId
            span_id: spanId
            stack_trace: stack_trace
    - labels:
        level:
    - timestamp:
        source: timestamp
        format: RFC3339Nano
    - output:
        source: output